sudo: required
dist: xenial
branches:
        only:
                - master
                - tests
language: python
python:
        - "3.5"
        - "3.6"
        - "3.7"

addons:
        postgresql: "10"
        apt:
                packages:
                        - postgresql-10
                        - postgresql-client-10
env:
  global:
  - PGPORT=5432

services:
        - postgresql
install:
        - "pip install -r requirements.txt"
        - "pip install pylint requests"

before_script:
        - psql -U postgres -f schema.sql
        - "cp config.py.example config.py"


script:
        - "pylint main.py gc.py stats.py"
        - "python3 main.py &"
        - "pytest tests.py"
