# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, tests ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build Python ${{ matrix.python_version }} and ${{ matrix.os }}
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        python_version: ['3.5', '3.6', '3.7', '3.8', '3.9', '3.10']
        psql_version: ['13']
        os: [ubuntu-latest]


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

   
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.3.2
        with:
          python-version: ${{ matrix.python_version }} # optional, default is 3.x
          architecture: x64
          
      - name: Setup PostgreSQL
        run: |
          apt update
          apt install --yes --no-install-recommends postgresql-client-${{ matrix.psql_version }} postgresql-${{ matrix.psql_version }}

        
      - name: Setup Schema
        run: psql -U postgres -f schema.sql
      - name: Install Main Dependencies
        run: pip install -r requirements.txt
      - name: Install Test Dependencies
        run: pip install pylint requests
      - name: Setup Config
        run: cp config.py.example config.py
      - name: Lint Code
        run: pylint main.py gc.py stats.py
      - name: Run Main
        run: python3 main.py &
      - name: Run Tests
        run: pytest tests.py

         
